version: "3.9"

services:
  db:
    image: docker.io/mysql:8.0
    container_name: mysql_gestao
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: gestao_links
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:Z
    restart: always

  phpmyadmin:
    image: docker.io/phpmyadmin:latest
    container_name: phpmyadmin_gestao
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 123456
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

volumes:
  db_data:

