-- Criar organização inicial (se não existir)
INSERT IGNORE INTO organizations (id, name)
VALUES (1, 'Default Organization');

-- Criar usuário admin com senha em branco (se não existir)
INSERT IGNORE INTO users (
  organization_id,
  name,
  email,
  password_hash,
  role,
  hourly_rate,
  active
) VALUES (
  1,
  'admin',
  'admin@example.com',
  '$2b$12$3uMGtFSiifBFyNolqomN5.G.yAbQWLwv0/1EdcvcC5sBw2Mi2.C0u',
  'admin',
  NULL,
  1
);
INSERT INTO modules (code, organization_id, label, description, active, created_at, updated_at)
VALUES
('SIGAATF',1,'Ativo fixo','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGACOM',1,'Compras','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAEST',1,'Estoque e Custos','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAFAT',1,'Faturamento','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAFIN',1,'Financeiro','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAFIS',1,'Livros Fiscais','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAPCP',1,'Planejamento e controle de produção','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGALOJA',1,'Operações de PDV e retaguarda','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGATMK',1,'Telemarketing, Televendas e Telecobrança','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAPON',1,'Ponto eletrônico','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGATCF',1,'Terminal de Consulta do Funcionário','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGARSP',1,'Recrutamento e Seleção Pessoal','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAQIE',1,'Inspeção de Entradas','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAQMT',1,'Metrologia (laboratório)','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAFRT',1,'Front Loja','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAQDO',1,'Controle de documentos','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAQIP',1,'Inspeção de Processos','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGATRM',1,'Treinamento','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGATEC',1,'Gestão de Serviços','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAPLS',1,'Plano de Saúde','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGACTB',1,'Contabilidade Gerencial','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAQNC',1,'Controle de Não-Conformidades','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAQAD',1,'Controle de Auditoria','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAOMS',1,'OMS – Gestão de Distribuição','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGACSA',1,'Cargos e Salários','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAWMS',1,'Gestão de Armazéns','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGATMS',1,'Gestão de Transportes','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAPMS',1,'Gestão de Projetos','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGACDA',1,'Controle de Direitos Autorais','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAACD',1,'Automação e Coleta de Dados','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAPPAP',1,'Processo de Aprovação de Peças de Produção (PPAP)','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAAPD',1,'Avaliação e Pesquisa de Desempenho','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAPCO',1,'Planejamento e Controle Orçamentário','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAAPT',1,'Acompanhamento de processos trabalhistas','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAAGR',1,'Gestão Agrícola','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAGCT',1,'Gestão de Contratos','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAORG',1,'Arquitetura organizacional','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGACRM',1,'Customer Relationship Management (CRM)','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAJURI',1,'Gestão de Assuntos Jurídicos','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAPFS',1,'Pré faturamento de Serviço','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('TOTVSGFE',1,'Frete Embarcador','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('TOTVSSFC',1,'Chão de Fábrica','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGADPR',1,'Desenvolvedor de Produtos','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGATAF',1,'TOTVS Automação Fiscal','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAGCP',1,'Gestão de Compras Públicas','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAGTP',1,'Gestão de transporte de passageiro','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGACFG',1,'Configurador','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('SIGAEIC',1,'Comércio Exterior','',1,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6));
